module.exports = [
    'core/debounce.js',
    'core/link.js',
    'core/selection-region.js',
    'core/table.js',
    'core/tools.js',
    'core/uicore.js',
    'plugins/*.js',
    'ui/react/src/oop/lang.js',
    'ui/react/src/oop/oop.js',
    'ui/react/src/oop/attribute.js',
    'ui/react/src/oop/base.js',
    'ui/react/src/selections/selections.js',
    'ui/react/src/adapter/alloy-editor-adapter.js*',
    'ui/react/src/components/base/*.js*',
    'ui/react/src/components/buttons/*.js*',
    'ui/react/src/components/toolbars/*.js*',
    'ui/react/src/components/main.js*'
];